# Generated by Django 5.2.6 on 2025-11-02 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_favoritoproducto_delete_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritoproducto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Favorito de Producto', 'verbose_name_plural': 'Favoritos de Productos'},
        ),
        migrations.AlterField(
            model_name='favoritoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='favoritoproducto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_productos', to=settings.AUTH_USER_MODEL),
        ),
    ]
