# Generated by Django 5.2.6 on 2025-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_favoritoproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('C$', 'Córdoba (C$)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (€)')], default='C$', max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_precio',
            field=models.CharField(choices=[('unidad', 'Por Unidad'), ('paquete', 'Por Paquete'), ('docena', 'Por Docena'), ('otro', 'Otro')], default='unidad', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto antigua (mantener)', null=True, upload_to='productos/'),
        ),
    ]
