# Generated by Django 5.2.6 on 2025-10-29 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('portada', 'Destacado en Portada'), ('categoria', 'Primero en Categoría')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dias', models.PositiveIntegerField()),
                ('pagadito_id', models.CharField(max_length=100, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
