# Generated by Django 5.2.6 on 2025-10-31 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_categorianegocio_options_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='anuncios/')),
                ('enlace', models.URLField(blank=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='pagadito_id',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='promocion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocion',
            name='plan',
            field=models.CharField(choices=[('24h', '24 horas - $1.00'), ('3d', '3 días - $2.50'), ('7d', '7 días - $5.00')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio'),
            preserve_default=False,
        ),
    ]
