# Generated by Django 5.2.6 on 2025-11-01 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Ej: tools, paint-brush, car-repair', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_precio', models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Por Día'), ('proyecto', 'Por Proyecto'), ('fijo', 'Precio Fijo')], default='hora', max_length=10)),
                ('experiencia', models.CharField(blank=True, help_text='Ej: 5 años, Certificado', max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_destacado', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.categoriaservicio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('servicio', 'usuario')},
            },
        ),
    ]
