# Generated by Django 5.2.6 on 2025-11-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalificacionServicio',
        ),
    ]
