# Generated by Django 5.2.6 on 2025-11-02 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_favoritoservicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritoservicio',
            options={'ordering': ['-fecha'], 'verbose_name': 'Favorito de Servicio', 'verbose_name_plural': 'Favoritos de Servicios'},
        ),
        migrations.AlterField(
            model_name='favoritoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='favoritoservicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_servicios', to=settings.AUTH_USER_MODEL),
        ),
    ]
