# Generated by Django 5.2.6 on 2025-11-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_favoritoservicio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='servicio',
            name='moneda',
            field=models.CharField(choices=[('C$', 'Córdoba (C$)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (€)')], default='C$', max_length=5),
        ),
    ]
