# Generated by Django 5.2.6 on 2025-11-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_remove_servicio_telefono_remove_servicio_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaservicio',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías de Servicio'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
