# Generated by Django 5.2.6 on 2025-11-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_foto_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
