# Generated by Django 5.2.6 on 2025-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: +50557277494, +15551234567', max_length=16, null=True),
        ),
    ]
