# Generated by Django 5.2.6 on 2025-11-01 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_categorianegocio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='categorianegocio',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Categorías de Negocio'},
        ),
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='negocio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Negocios'},
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_dadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categorianegocio',
            name='icono',
            field=models.CharField(blank=True, help_text='Ej: scissors, car, coffee', max_length=50),
        ),
        migrations.AlterField(
            model_name='categorianegocio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_negocios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to='negocios.categorianegocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
