# Generated by Django 5.2.6 on 2025-11-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_alter_calificacion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
