# Generated by Django 5.2.6 on 2025-11-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_delete_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['-fecha'], 'verbose_name': 'Favorito de Negocio', 'verbose_name_plural': 'Favoritos de Negocios'},
        ),
    ]
