# Generated by Django 5.2.6 on 2025-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_alter_favorito_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
