# Generated by Django 5.2.6 on 2025-11-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_remove_negocio_whatsapp_alter_negocio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_5',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='negocios/'),
        ),
    ]
